// DADOS TEMPORÁRIOS

export let role = "admin";

export const teachersData = [
  {
    id: 1,
    teacherId: "1234567890",
    name: "João Mbala",
    email: "joao@mbala.ao",
    foto: "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "923456789",
    subjects: ["Matemática", "Geometria"],
    classes: ["7A", "8B", "9C"],
    address: "Rua da Missão, 123, Luanda",
  },
  {
    id: 2,
    teacherId: "1234567890",
    name: "Ana Tchissola",
    email: "ana@tchissola.ao",
    foto: "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "912345678",
    subjects: ["Física", "Química"],
    classes: ["10A", "11B", "9C"],
    address: "Av. 4 de Fevereiro, 456, Luanda",
  },
  {
    id: 3,
    teacherId: "1234567890",
    name: "Pedro Domingos",
    email: "pedro@domingos.ao",
    foto: "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "924567890",
    subjects: ["Biologia"],
    classes: ["10A", "11B", "9C"],
    address: "Rua Major Kanhangulo, 789, Luanda",
  },
  {
    id: 4,
    teacherId: "1234567890",
    name: "Maria Ngueve",
    email: "maria@ngueve.ao",
    foto: "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "913456789",
    subjects: ["História"],
    classes: ["10A", "11B", "9C"],
    address: "Rua Amílcar Cabral, 101, Benguela",
  },
  {
    id: 5,
    teacherId: "1234567890",
    name: "Teresa Kamara",
    email: "teresa@kamara.ao",
    foto: "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "925678901",
    subjects: ["Música", "História"],
    classes: ["10A", "11B", "9C"],
    address: "Rua Direita, 202, Huambo",
  },
  {
    id: 6,
    teacherId: "1234567890",
    name: "Rosa Valentim",
    email: "rosa@valentim.ao",
    foto: "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "914567890",
    subjects: ["Física"],
    classes: ["10A", "11B", "9C"],
    address: "Av. Norton de Matos, 303, Lubango",
  },
  {
    id: 7,
    teacherId: "1234567890",
    name: "Manuel Catumbela",
    email: "manuel@catumbela.ao",
    foto: "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "926789012",
    subjects: ["Inglês", "Francês"],
    classes: ["10A", "11B", "9C"],
    address: "Rua da Praia, 404, Cabinda",
  },
  {
    id: 8,
    teacherId: "1234567890",
    name: "Luísa Fernandes",
    email: "luisa@fernandes.ao",
    foto: "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "915678901",
    subjects: ["Matemática", "Geometria"],
    classes: ["10A", "11B", "9C"],
    address: "Rua do Comércio, 505, Malanje",
  },
  {
    id: 9,
    teacherId: "1234567890",
    name: "Carlos Tavares",
    email: "carlos@tavares.ao",
    foto: "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "927890123",
    subjects: ["Literatura", "Inglês"],
    classes: ["10A", "11B", "9C"],
    address: "Av. da Independência, 606, Namibe",
  },
  {
    id: 10,
    teacherId: "1234567890",
    name: "Helena Cassule",
    email: "helena@cassule.ao",
    foto: "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "916789012",
    subjects: ["Biologia"],
    classes: ["10A", "11B", "9C"],
    address: "Rua Principal, 707, Uíge",
  },
];

export const studentsData = [
  {
    id: 1,
    studentId: "STU001",
    name: "Kiala Mbala",
    email: "kiala@mbala.ao",
    foto: "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "923111111",
    classe: 7,
    turma: "7A",
    address: "Rua da Missão, 123, Luanda",
  },
  {
    id: 2,
    studentId: "STU002",
    name: "Ndalu Ngueve",
    email: "ndalu@ngueve.ao",
    foto: "https://images.pexels.com/photos/1139743/pexels-photo-1139743.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "912222222",
    classe: 8,
    turma: "8B",
    address: "Av. 4 de Fevereiro, 456, Luanda",
  },
  {
    id: 3,
    studentId: "STU003",
    name: "Tchissola Santos",
    email: "tchissola@santos.ao",
    foto: "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "924333333",
    classe: 7,
    turma: "7A",
    address: "Rua Major Kanhangulo, 789, Luanda",
  },
  {
    id: 4,
    studentId: "STU004",
    name: "Amara Costa",
    email: "amara@costa.ao",
    foto: "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "913444444",
    classe: 9,
    turma: "9C",
    address: "Rua Amílcar Cabral, 101, Benguela",
  },
  {
    id: 5,
    studentId: "STU005",
    name: "Djesus Ferreira",
    email: "djesus@ferreira.ao",
    foto: "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "925555555",
    classe: 8,
    turma: "8B",
    address: "Rua Direita, 202, Huambo",
  },
  {
    id: 6,
    studentId: "STU006",
    name: "Nzinga Rocha",
    email: "nzinga@rocha.ao",
    foto: "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "914666666",
    classe: 7,
    turma: "7A",
    address: "Av. Norton de Matos, 303, Lubango",
  },
  {
    id: 7,
    studentId: "STU007",
    name: "Kalulu Lima",
    email: "kalulu@lima.ao",
    foto: "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "926777777",
    classe: 9,
    turma: "9C",
    address: "Rua da Praia, 404, Cabinda",
  },
  {
    id: 8,
    studentId: "STU008",
    name: "Yara Mendes",
    email: "yara@mendes.ao",
    foto: "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "915888888",
    classe: 8,
    turma: "8B",
    address: "Rua do Comércio, 505, Malanje",
  },
  {
    id: 9,
    studentId: "STU009",
    name: "Bento Almeida",
    email: "bento@almeida.ao",
    foto: "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "927999999",
    classe: 7,
    turma: "7A",
    address: "Av. da Independência, 606, Namibe",
  },
  {
    id: 10,
    studentId: "STU010",
    name: "Esperança Souza",
    email: "esperanca@souza.ao",
    foto: "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "916000000",
    classe: 9,
    turma: "9C",
    address: "Rua Principal, 707, Uíge",
  },
];

export const parentsData = [
  {
    id: 1,
    name: "António Mbala",
    email: "antonio@mbala.ao",
    foto: "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "923456001",
    students: ["Kiala Mbala"],
    address: "Rua da Missão, 123, Luanda",
  },
  {
    id: 2,
    name: "Graça Ngueve",
    email: "graca@ngueve.ao",
    foto: "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "912456002",
    students: ["Ndalu Ngueve"],
    address: "Av. 4 de Fevereiro, 456, Luanda",
  },
  {
    id: 3,
    name: "Francisco Santos",
    email: "francisco@santos.ao",
    foto: "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "924456003",
    students: ["Tchissola Santos"],
    address: "Rua Major Kanhangulo, 789, Luanda",
  },
  {
    id: 4,
    name: "Josefa Costa",
    email: "josefa@costa.ao",
    foto: "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "913456004",
    students: ["Amara Costa", "Djesus Ferreira"],
    address: "Rua Amílcar Cabral, 101, Benguela",
  },
  {
    id: 5,
    name: "Domingos Ferreira",
    email: "domingos@ferreira.ao",
    foto: "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "925456005",
    students: ["Djesus Ferreira"],
    address: "Rua Direita, 202, Huambo",
  },
  {
    id: 6,
    name: "Belarmina Rocha",
    email: "belarmina@rocha.ao",
    foto: "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "914456006",
    students: ["Nzinga Rocha"],
    address: "Av. Norton de Matos, 303, Lubango",
  },
  {
    id: 7,
    name: "Augusto Lima",
    email: "augusto@lima.ao",
    foto: "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "926456007",
    students: ["Kalulu Lima", "Yara Mendes"],
    address: "Rua da Praia, 404, Cabinda",
  },
  {
    id: 8,
    name: "Conceição Mendes",
    email: "conceicao@mendes.ao",
    foto: "https://images.pexels.com/photos/1139743/pexels-photo-1139743.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "915456008",
    students: ["Yara Mendes"],
    address: "Rua do Comércio, 505, Malanje",
  },
  {
    id: 9,
    name: "Mateus Almeida",
    email: "mateus@almeida.ao",
    foto: "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "927456009",
    students: ["Bento Almeida"],
    address: "Av. da Independência, 606, Namibe",
  },
  {
    id: 10,
    name: "Filomena Souza",
    email: "filomena@souza.ao",
    foto: "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "916456010",
    students: ["Esperança Souza"],
    address: "Rua Principal, 707, Uíge",
  },
];

export const subjectsData = [
  { id: 1, name: "Matemática", professores: ["João Mbala", "Luísa Fernandes"] },
  { id: 2, name: "Inglês", professores: ["Manuel Catumbela", "Carlos Tavares"] },
  { id: 3, name: "Física", professores: ["Ana Tchissola", "Rosa Valentim"] },
  { id: 4, name: "Química", professores: ["Ana Tchissola", "Rosa Valentim"] },
  { id: 5, name: "Biologia", professores: ["Pedro Domingos", "Helena Cassule"] },
  { id: 6, name: "História", professores: ["Maria Ngueve", "Teresa Kamara"] },
  { id: 7, name: "Geografia", professores: ["Teresa Kamara", "Maria Ngueve"] },
  { id: 8, name: "Arte", professores: ["Rosa Valentim", "Teresa Kamara"] },
  { id: 9, name: "Música", professores: ["Teresa Kamara", "Rosa Valentim"] },
  { id: 10, name: "Literatura", professores: ["Carlos Tavares", "Manuel Catumbela"] },
];

export const examsData = [
  {
    id: 1,
    materia: "Matemática",
    turma: "7A",
    professor: "João Mbala",
    data: "2026-05-10",
  },
  {
    id: 2,
    materia: "Inglês",
    turma: "8B",
    professor: "Manuel Catumbela",
    data: "2026-05-11",
  },
  // ...
];

export const classesData = [
  { id: 1, name: "7A", capacity: 30, grade: 7, supervisor: "João Mbala" },
  { id: 2, name: "7B", capacity: 28, grade: 7, supervisor: "Ana Tchissola" },
  { id: 3, name: "8A", capacity: 32, grade: 8, supervisor: "Pedro Domingos" },
  { id: 4, name: "8B", capacity: 30, grade: 8, supervisor: "Maria Ngueve" },
  { id: 5, name: "9A", capacity: 25, grade: 9, supervisor: "Teresa Kamara" },
  { id: 6, name: "9B", capacity: 27, grade: 9, supervisor: "Rosa Valentim" },
  { id: 7, name: "9C", capacity: 30, grade: 9, supervisor: "Manuel Catumbela" },
  { id: 8, name: "10A", capacity: 28, grade: 10, supervisor: "Luísa Fernandes" },
  { id: 9, name: "11B", capacity: 30, grade: 11, supervisor: "Carlos Tavares" },
  { id: 10, name: "12A", capacity: 26, grade: 12, supervisor: "Helena Cassule" },
];

export const lessonsData = [
  { id: 1, subject: "Matemática", class: "7A", teacher: "João Mbala", day: "Segunda", startTime: "07:30", endTime: "08:50" },
  { id: 2, subject: "Inglês", class: "7A", teacher: "Manuel Catumbela", day: "Segunda", startTime: "09:00", endTime: "09:45" },
  { id: 3, subject: "Biologia", class: "8B", teacher: "Pedro Domingos", day: "Terça", startTime: "07:30", endTime: "08:50" },
  { id: 4, subject: "Física", class: "8B", teacher: "Ana Tchissola", day: "Terça", startTime: "09:00", endTime: "10:20" },
  { id: 5, subject: "Química", class: "9C", teacher: "Ana Tchissola", day: "Quarta", startTime: "07:30", endTime: "08:50" },
  { id: 6, subject: "História", class: "7A", teacher: "Maria Ngueve", day: "Quarta", startTime: "09:00", endTime: "10:20" },
  { id: 7, subject: "Geografia", class: "9A", teacher: "Teresa Kamara", day: "Quinta", startTime: "07:30", endTime: "08:50" },
  { id: 8, subject: "Literatura", class: "11B", teacher: "Carlos Tavares", day: "Quinta", startTime: "09:00", endTime: "10:20" },
  { id: 9, subject: "Música", class: "12A", teacher: "Teresa Kamara", day: "Sexta", startTime: "07:30", endTime: "08:50" },
  { id: 10, subject: "Arte", class: "9B", teacher: "Rosa Valentim", day: "Sexta", startTime: "09:00", endTime: "10:20" },
];

export const assignmentsData = [
  { id: 1, subject: "Matemática", class: "7A", teacher: "João Mbala", dueDate: "2026-03-10" },
  { id: 2, subject: "Inglês", class: "8B", teacher: "Manuel Catumbela", dueDate: "2026-03-12" },
  { id: 3, subject: "Biologia", class: "9C", teacher: "Pedro Domingos", dueDate: "2026-03-15" },
  { id: 4, subject: "Física", class: "7A", teacher: "Ana Tchissola", dueDate: "2026-03-18" },
  { id: 5, subject: "História", class: "8B", teacher: "Maria Ngueve", dueDate: "2026-03-20" },
  { id: 6, subject: "Química", class: "9A", teacher: "Ana Tchissola", dueDate: "2026-03-22" },
  { id: 7, subject: "Geografia", class: "11B", teacher: "Teresa Kamara", dueDate: "2026-03-25" },
  { id: 8, subject: "Literatura", class: "12A", teacher: "Carlos Tavares", dueDate: "2026-03-28" },
  { id: 9, subject: "Música", class: "7A", teacher: "Teresa Kamara", dueDate: "2026-04-01" },
  { id: 10, subject: "Arte", class: "9B", teacher: "Rosa Valentim", dueDate: "2026-04-05" },
];

export const resultsData = [
  { id: 1, student: "Kiala Mbala", subject: "Matemática", score: 85, type: "Prova", date: "2026-02-15" },
  { id: 2, student: "Ndalu Ngueve", subject: "Inglês", score: 92, type: "Prova", date: "2026-02-15" },
  { id: 3, student: "Tchissola Santos", subject: "Biologia", score: 78, type: "Tarefa", date: "2026-02-18" },
  { id: 4, student: "Amara Costa", subject: "Física", score: 95, type: "Prova", date: "2026-02-20" },
  { id: 5, student: "Djesus Ferreira", subject: "História", score: 67, type: "Tarefa", date: "2026-02-22" },
  { id: 6, student: "Nzinga Rocha", subject: "Química", score: 88, type: "Prova", date: "2026-02-25" },
  { id: 7, student: "Kalulu Lima", subject: "Geografia", score: 73, type: "Tarefa", date: "2026-02-28" },
  { id: 8, student: "Yara Mendes", subject: "Literatura", score: 91, type: "Prova", date: "2026-03-01" },
  { id: 9, student: "Bento Almeida", subject: "Música", score: 86, type: "Tarefa", date: "2026-03-05" },
  { id: 10, student: "Esperança Souza", subject: "Arte", score: 94, type: "Prova", date: "2026-03-08" },
];

export const attendanceData = [
  { id: 1, student: "Kiala Mbala", date: "2026-02-27", status: "Presente" as const, class: "7A" },
  { id: 2, student: "Ndalu Ngueve", date: "2026-02-27", status: "Presente" as const, class: "8B" },
  { id: 3, student: "Tchissola Santos", date: "2026-02-27", status: "Ausente" as const, class: "7A" },
  { id: 4, student: "Amara Costa", date: "2026-02-27", status: "Presente" as const, class: "9C" },
  { id: 5, student: "Djesus Ferreira", date: "2026-02-27", status: "Atrasado" as const, class: "8B" },
  { id: 6, student: "Nzinga Rocha", date: "2026-02-26", status: "Presente" as const, class: "7A" },
  { id: 7, student: "Kalulu Lima", date: "2026-02-26", status: "Presente" as const, class: "9C" },
  { id: 8, student: "Yara Mendes", date: "2026-02-26", status: "Ausente" as const, class: "8B" },
  { id: 9, student: "Bento Almeida", date: "2026-02-26", status: "Presente" as const, class: "7A" },
  { id: 10, student: "Esperança Souza", date: "2026-02-26", status: "Atrasado" as const, class: "9C" },
];

export const messagesData = [
  { id: 1, from: "João Mbala", to: "Admin", subject: "Reunião pedagógica", message: "Precisamos agendar a reunião pedagógica do mês.", date: "2026-02-27", read: false },
  { id: 2, from: "Graça Ngueve", to: "João Mbala", subject: "Nota do Ndalu", message: "Gostaria de entender a nota do Ndalu na última prova.", date: "2026-02-26", read: true },
  { id: 3, from: "Admin", to: "Todos", subject: "Feriado escolar", message: "A escola estará encerrada no dia 03/03.", date: "2026-02-25", read: true },
  { id: 4, from: "Pedro Domingos", to: "Admin", subject: "Material de laboratório", message: "Precisamos repor os materiais do laboratório de biologia.", date: "2026-02-24", read: false },
  { id: 5, from: "António Mbala", to: "Maria Ngueve", subject: "Desempenho do filho", message: "Como está o desempenho do Kiala em história?", date: "2026-02-23", read: true },
  { id: 6, from: "Admin", to: "Professores", subject: "Conselho de classe", message: "O conselho de classe será na sexta-feira às 14h.", date: "2026-02-22", read: true },
  { id: 7, from: "Rosa Valentim", to: "Admin", subject: "Projecto de artes", message: "Vou precisar de um espaço extra para o projecto de artes.", date: "2026-02-21", read: false },
  { id: 8, from: "Josefa Costa", to: "Admin", subject: "Transporte escolar", message: "Há mudança nos horários do transporte escolar?", date: "2026-02-20", read: true },
  { id: 9, from: "Carlos Tavares", to: "Admin", subject: "Excursão literária", message: "Proposta de excursão à Feira do Livro para turmas 11B e 12A.", date: "2026-02-19", read: false },
  { id: 10, from: "Admin", to: "Encarregados", subject: "Calendário 2026", message: "Segue o calendário escolar actualizado para 2026.", date: "2026-02-18", read: true },
];

export const announcementsData = [
  { id: 1, title: "Início do trimestre", description: "As aulas do segundo trimestre começam no dia 10 de março.", date: "2026-02-27", class: "Todas" },
  { id: 2, title: "Feira de ciências", description: "A feira de ciências acontecerá no dia 20 de março. Inscrições abertas.", date: "2026-02-25", class: "9.ª classe" },
  { id: 3, title: "Reunião de encarregados", description: "Reunião de encarregados de educação no dia 15 de março às 19h.", date: "2026-02-24", class: "Todas" },
  { id: 4, title: "Campeonato desportivo", description: "Campeonato inter-turmas de futebol e basquetebol. Inscrições na secretaria.", date: "2026-02-22", class: "10.ª e 11.ª classe" },
  { id: 5, title: "Actualização do sistema", description: "O sistema ficará em manutenção no sábado das 22h às 06h.", date: "2026-02-20", class: "Todas" },
  { id: 6, title: "Exame de recurso", description: "Os exames de recurso acontecerão entre 25 e 28 de março.", date: "2026-02-18", class: "Todas" },
  { id: 7, title: "Excursão ao museu", description: "Excursão ao Museu Nacional de História Natural para turmas da 8.ª classe.", date: "2026-02-15", class: "8.ª classe" },
  { id: 8, title: "Uniforme novo", description: "O novo uniforme escolar já está disponível na secretaria.", date: "2026-02-12", class: "Todas" },
  { id: 9, title: "Vacinação", description: "Campanha de vacinação na escola no dia 05 de março.", date: "2026-02-10", class: "Todas" },
  { id: 10, title: "Matrículas abertas", description: "Matrículas para o próximo ano já estão abertas.", date: "2026-02-08", class: "Todas" },
];

export const calendarEvents = [
  // === SEGUNDA-FEIRA – 02/02/2026 ===
  {
    title: "Matemática",
    allDay: false,
    start: new Date(2026, 1, 2, 7, 30),
    end: new Date(2026, 1, 2, 8, 50),
    type: "math",
    teacher: "João Mbala",
    room: "Sala 101",
  },
  {
    title: "Inglês",
    allDay: false,
    start: new Date(2026, 1, 2, 9, 0),
    end: new Date(2026, 1, 2, 9, 45),
    type: "english",
    teacher: "Manuel Catumbela",
    room: "Sala 205",
  },
  {
    title: "Biologia",
    allDay: false,
    start: new Date(2026, 1, 2, 10, 0),
    end: new Date(2026, 1, 2, 11, 20),
    type: "biology",
    teacher: "Pedro Domingos",
    room: "Lab 1",
  },
  // === TERÇA-FEIRA – 03/02/2026 ===
  {
    title: "Física",
    allDay: false,
    start: new Date(2026, 1, 3, 7, 30),
    end: new Date(2026, 1, 3, 8, 50),
    type: "physics",
    teacher: "Ana Tchissola",
    room: "Lab 2",
  },
  {
    title: "Química",
    allDay: false,
    start: new Date(2026, 1, 3, 9, 0),
    end: new Date(2026, 1, 3, 10, 20),
    type: "chemistry",
    teacher: "Ana Tchissola",
    room: "Lab 3",
  },
  {
    title: "História",
    allDay: false,
    start: new Date(2026, 1, 3, 10, 30),
    end: new Date(2026, 1, 3, 11, 50),
    type: "history",
    teacher: "Maria Ngueve",
    room: "Sala 102",
  },
  // === QUARTA-FEIRA – 04/02/2026 ===
  {
    title: "Geografia",
    allDay: false,
    start: new Date(2026, 1, 4, 7, 30),
    end: new Date(2026, 1, 4, 8, 50),
    type: "geography",
    teacher: "Teresa Kamara",
    room: "Sala 103",
  },
  {
    title: "Literatura",
    allDay: false,
    start: new Date(2026, 1, 4, 9, 0),
    end: new Date(2026, 1, 4, 10, 20),
    type: "literature",
    teacher: "Carlos Tavares",
    room: "Sala 204",
  },
  {
    title: "Matemática",
    allDay: false,
    start: new Date(2026, 1, 4, 10, 30),
    end: new Date(2026, 1, 4, 11, 50),
    type: "math",
    teacher: "Luísa Fernandes",
    room: "Sala 101",
  },
  // === QUINTA-FEIRA – 05/02/2026 ===
  {
    title: "Música",
    allDay: false,
    start: new Date(2026, 1, 5, 7, 30),
    end: new Date(2026, 1, 5, 8, 50),
    type: "music",
    teacher: "Teresa Kamara",
    room: "Auditório",
  },
  {
    title: "Arte",
    allDay: false,
    start: new Date(2026, 1, 5, 9, 0),
    end: new Date(2026, 1, 5, 10, 20),
    type: "art",
    teacher: "Rosa Valentim",
    room: "Ateliê",
  },
  {
    title: "Física",
    allDay: false,
    start: new Date(2026, 1, 5, 10, 30),
    end: new Date(2026, 1, 5, 11, 50),
    type: "physics",
    teacher: "Rosa Valentim",
    room: "Lab 2",
  },
  // === SEXTA-FEIRA – 06/02/2026 ===
  {
    title: "Inglês",
    allDay: false,
    start: new Date(2026, 1, 6, 7, 30),
    end: new Date(2026, 1, 6, 8, 50),
    type: "english",
    teacher: "Manuel Catumbela",
    room: "Sala 205",
  },
  {
    title: "Biologia",
    allDay: false,
    start: new Date(2026, 1, 6, 9, 0),
    end: new Date(2026, 1, 6, 10, 20),
    type: "biology",
    teacher: "Helena Cassule",
    room: "Lab 1",
  },
  {
    title: "História",
    allDay: false,
    start: new Date(2026, 1, 6, 10, 30),
    end: new Date(2026, 1, 6, 11, 50),
    type: "history",
    teacher: "Maria Ngueve",
    room: "Sala 102",
  },
];
