// DADOS TEMPORÁRIOS

export let role = "admin";

export const teachersData = [
  {
    id: 1,
    teacherId: "1234567890",
    name: "João Silva",
    email: "joao@silva.com",
    foto: "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "11999999999",
    subjects: ["Matemática", "Geometria"],
    classes: ["1B", "2A", "3C"],
    address: "Rua Principal, 123, São Paulo, SP",
  },
  {
    id: 2,
    teacherId: "1234567890",
    name: "Joana Santos",
    email: "joana@santos.com",
    foto: "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "11999999999",
    subjects: ["Física", "Química"],
    classes: ["5A", "4B", "3C"],
    address: "Avenida Central, 456, Rio de Janeiro, RJ",
  },
  {
    id: 3,
    teacherId: "1234567890",
    name: "Miguel Geller",
    email: "miguel@geller.com",
    foto: "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "11999999999",
    subjects: ["Biologia"],
    classes: ["5A", "4B", "3C"],
    address: "Rua das Flores, 789, Curitiba, PR",
  },
  {
    id: 4,
    teacherId: "1234567890",
    name: "Jayme Franco",
    email: "jayme@gmail.com",
    foto: "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "11999999999",
    subjects: ["História"],
    classes: ["5A", "4B", "3C"],
    address: "Rua XV de Novembro, 101, Blumenau, SC",
  },
  {
    id: 5,
    teacherId: "1234567890",
    name: "Jane Smith",
    email: "jane@gmail.com",
    foto: "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "11999999999",
    subjects: ["Música", "História"],
    classes: ["5A", "4B", "3C"],
    address: "Alameda Santos, 202, São Paulo, SP",
  },
  {
    id: 6,
    teacherId: "1234567890",
    name: "Ana Santiago",
    email: "anna@gmail.com",
    foto: "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "11999999999",
    subjects: ["Física"],
    classes: ["5A", "4B", "3C"],
    address: "Rua do Sol, 303, Salvador, BA",
  },
  {
    id: 7,
    teacherId: "1234567890",
    name: "Allan Preto",
    email: "allan@preto.com",
    foto: "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "11999999999",
    subjects: ["Inglês", "Espanhol"],
    classes: ["5A", "4B", "3C"],
    address: "Rua da Paz, 404, Porto Alegre, RS",
  },
  {
    id: 8,
    teacherId: "1234567890",
    name: "Ofélia Castro",
    email: "ofelia@castro.com",
    foto: "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "11999999999",
    subjects: ["Matemática", "Geometria"],
    classes: ["5A", "4B", "3C"],
    address: "Avenida Brasil, 505, Belo Horizonte, MG",
  },
  {
    id: 9,
    teacherId: "1234567890",
    name: "Derek Briggs",
    email: "derek@briggs.com",
    foto: "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "11999999999",
    subjects: ["Literatura", "Inglês"],
    classes: ["5A", "4B", "3C"],
    address: "Rua Amazonas, 606, Manaus, AM",
  },
  {
    id: 10,
    teacherId: "1234567890",
    name: "João Glover",
    email: "joao@glover.com",
    foto: "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "11999999999",
    subjects: ["Biologia"],
    classes: ["5A", "4B", "3C"],
    address: "Rua Maranhão, 707, Brasília, DF",
  },
];

export const studentsData = [
  {
    id: 1,
    studentId: "STU001",
    name: "Joãozinho Silva",
    email: "joaozinho@silva.com",
    foto: "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "11999999999",
    serie: 5,
    turma: "1B",
    address: "Rua Principal, 123, São Paulo, SP",
  },
  {
    id: 2,
    studentId: "STU002",
    name: "Maria Oliveira",
    email: "maria@oliveira.com",
    foto: "https://images.pexels.com/photos/1139743/pexels-photo-1139743.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "11988888888",
    serie: 6,
    turma: "2A",
    address: "Avenida Central, 456, Rio de Janeiro, RJ",
  },
  {
    id: 3,
    studentId: "STU003",
    name: "Pedro Santos",
    email: "pedro@santos.com",
    foto: "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "11977777777",
    serie: 5,
    turma: "1B",
    address: "Rua das Flores, 789, Curitiba, PR",
  },
  {
    id: 4,
    studentId: "STU004",
    name: "Ana Costa",
    email: "ana@costa.com",
    foto: "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "11966666666",
    serie: 7,
    turma: "3C",
    address: "Rua XV de Novembro, 101, Blumenau, SC",
  },
  {
    id: 5,
    studentId: "STU005",
    name: "Lucas Ferreira",
    email: "lucas@ferreira.com",
    foto: "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "11955555555",
    serie: 6,
    turma: "2A",
    address: "Alameda Santos, 202, São Paulo, SP",
  },
  {
    id: 6,
    studentId: "STU006",
    name: "Camila Rocha",
    email: "camila@rocha.com",
    foto: "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "11944444444",
    serie: 5,
    turma: "1B",
    address: "Rua do Sol, 303, Salvador, BA",
  },
  {
    id: 7,
    studentId: "STU007",
    name: "Gabriel Lima",
    email: "gabriel@lima.com",
    foto: "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "11933333333",
    serie: 7,
    turma: "3C",
    address: "Rua da Paz, 404, Porto Alegre, RS",
  },
  {
    id: 8,
    studentId: "STU008",
    name: "Isabela Mendes",
    email: "isabela@mendes.com",
    foto: "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "11922222222",
    serie: 6,
    turma: "2A",
    address: "Avenida Brasil, 505, Belo Horizonte, MG",
  },
  {
    id: 9,
    studentId: "STU009",
    name: "Rafael Almeida",
    email: "rafael@almeida.com",
    foto: "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "11911111111",
    serie: 5,
    turma: "1B",
    address: "Rua Amazonas, 606, Manaus, AM",
  },
  {
    id: 10,
    studentId: "STU010",
    name: "Larissa Souza",
    email: "larissa@souza.com",
    foto: "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "11900000000",
    serie: 7,
    turma: "3C",
    address: "Rua Maranhão, 707, Brasília, DF",
  },
];

export const parentsData = [
  {
    id: 1,
    name: "Carlos Silva",
    email: "carlos@silva.com",
    foto: "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "11999999999",
    students: ["Joãozinho Silva"],
    address: "Rua Principal, 123, São Paulo, SP",
  },
  {
    id: 2,
    name: "Fernanda Oliveira",
    email: "fernanda@oliveira.com",
    foto: "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "11988888888",
    students: ["Maria Oliveira"],
    address: "Avenida Central, 456, Rio de Janeiro, RJ",
  },
  {
    id: 3,
    name: "Roberto Santos",
    email: "roberto@santos.com",
    foto: "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "11977777777",
    students: ["Pedro Santos"],
    address: "Rua das Flores, 789, Curitiba, PR",
  },
  {
    id: 4,
    name: "Patrícia Costa",
    email: "patricia@costa.com",
    foto: "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "11966666666",
    students: ["Ana Costa", "Lucas Ferreira"],
    address: "Rua XV de Novembro, 101, Blumenau, SC",
  },
  {
    id: 5,
    name: "Marcos Ferreira",
    email: "marcos@ferreira.com",
    foto: "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "11955555555",
    students: ["Lucas Ferreira"],
    address: "Alameda Santos, 202, São Paulo, SP",
  },
  {
    id: 6,
    name: "Juliana Rocha",
    email: "juliana@rocha.com",
    foto: "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "11944444444",
    students: ["Camila Rocha"],
    address: "Rua do Sol, 303, Salvador, BA",
  },
  {
    id: 7,
    name: "Eduardo Lima",
    email: "eduardo@lima.com",
    foto: "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "11933333333",
    students: ["Gabriel Lima", "Isabela Mendes"],
    address: "Rua da Paz, 404, Porto Alegre, RS",
  },
  {
    id: 8,
    name: "Sandra Mendes",
    email: "sandra@mendes.com",
    foto: "https://images.pexels.com/photos/1139743/pexels-photo-1139743.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "11922222222",
    students: ["Isabela Mendes"],
    address: "Avenida Brasil, 505, Belo Horizonte, MG",
  },
  {
    id: 9,
    name: "Ricardo Almeida",
    email: "ricardo@almeida.com",
    foto: "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "11911111111",
    students: ["Rafael Almeida"],
    address: "Rua Amazonas, 606, Manaus, AM",
  },
  {
    id: 10,
    name: "Claudia Souza",
    email: "claudia@souza.com",
    foto: "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "11900000000",
    students: ["Larissa Souza"],
    address: "Rua Maranhão, 707, Brasília, DF",
  },
];

export const subjectsData = [
  { id: 1, name: "Matemática", professores: ["Alice Phelps", "Russell Davidson"] },
  { id: 2, name: "Inglês", professores: ["Manuel Becker", "Eddie Chavez"] },
  { id: 3, name: "Física", professores: ["Lola Newman", "Darrell Delgado"] },
  { id: 4, name: "Química", professores: ["Nathan Kelly", "Benjamin Snyder"] },
  { id: 5, name: "Biologia", professores: ["Alma Benson", "Lina Collier"] },
  { id: 6, name: "História", professores: ["Hannah Bowman", "Betty Obrien"] },
  { id: 7, name: "Geografia", professores: ["Lora French", "Sue Brady"] },
  { id: 8, name: "Arte", professores: ["Harriet Alvarado", "Mayme Keller"] },
  { id: 9, name: "Música", professores: ["Gertrude Roy", "Rosa Singleton"] },
  { id: 10, name: "Literatura", professores: ["Effie Lynch", "Brett Flowers"] },
];

export const examsData = [
  {
    id: 1,
    materia: "Matemática",
    turma: "1A",
    professor: "Martha Morris",
    data: "2026-05-10",
  },
  {
    id: 2,
    materia: "Inglês",
    turma: "2A",
    professor: "Randall Garcia",
    data: "2026-05-11",
  },
  // ...
];

export const classesData = [
  { id: 1, name: "1A", capacity: 30, grade: 1, supervisor: "João Silva" },
  { id: 2, name: "1B", capacity: 28, grade: 1, supervisor: "Joana Santos" },
  { id: 3, name: "2A", capacity: 32, grade: 2, supervisor: "Miguel Geller" },
  { id: 4, name: "2B", capacity: 30, grade: 2, supervisor: "Jayme Franco" },
  { id: 5, name: "3A", capacity: 25, grade: 3, supervisor: "Jane Smith" },
  { id: 6, name: "3B", capacity: 27, grade: 3, supervisor: "Ana Santiago" },
  { id: 7, name: "3C", capacity: 30, grade: 3, supervisor: "Allan Preto" },
  { id: 8, name: "4A", capacity: 28, grade: 4, supervisor: "Ofélia Castro" },
  { id: 9, name: "4B", capacity: 30, grade: 4, supervisor: "Derek Briggs" },
  { id: 10, name: "5A", capacity: 26, grade: 5, supervisor: "João Glover" },
];

export const lessonsData = [
  { id: 1, subject: "Matemática", class: "1A", teacher: "João Silva", day: "Segunda", startTime: "07:30", endTime: "08:50" },
  { id: 2, subject: "Inglês", class: "1A", teacher: "Allan Preto", day: "Segunda", startTime: "09:00", endTime: "09:45" },
  { id: 3, subject: "Biologia", class: "2A", teacher: "Miguel Geller", day: "Terça", startTime: "07:30", endTime: "08:50" },
  { id: 4, subject: "Física", class: "2A", teacher: "Joana Santos", day: "Terça", startTime: "09:00", endTime: "10:20" },
  { id: 5, subject: "Química", class: "3C", teacher: "Joana Santos", day: "Quarta", startTime: "07:30", endTime: "08:50" },
  { id: 6, subject: "História", class: "1B", teacher: "Jayme Franco", day: "Quarta", startTime: "09:00", endTime: "10:20" },
  { id: 7, subject: "Geografia", class: "3A", teacher: "Jane Smith", day: "Quinta", startTime: "07:30", endTime: "08:50" },
  { id: 8, subject: "Literatura", class: "4B", teacher: "Derek Briggs", day: "Quinta", startTime: "09:00", endTime: "10:20" },
  { id: 9, subject: "Música", class: "5A", teacher: "Jane Smith", day: "Sexta", startTime: "07:30", endTime: "08:50" },
  { id: 10, subject: "Arte", class: "3B", teacher: "Ana Santiago", day: "Sexta", startTime: "09:00", endTime: "10:20" },
];

export const assignmentsData = [
  { id: 1, subject: "Matemática", class: "1A", teacher: "João Silva", dueDate: "2026-03-10" },
  { id: 2, subject: "Inglês", class: "2A", teacher: "Allan Preto", dueDate: "2026-03-12" },
  { id: 3, subject: "Biologia", class: "3C", teacher: "Miguel Geller", dueDate: "2026-03-15" },
  { id: 4, subject: "Física", class: "1B", teacher: "Joana Santos", dueDate: "2026-03-18" },
  { id: 5, subject: "História", class: "2A", teacher: "Jayme Franco", dueDate: "2026-03-20" },
  { id: 6, subject: "Química", class: "3A", teacher: "Joana Santos", dueDate: "2026-03-22" },
  { id: 7, subject: "Geografia", class: "4B", teacher: "Jane Smith", dueDate: "2026-03-25" },
  { id: 8, subject: "Literatura", class: "5A", teacher: "Derek Briggs", dueDate: "2026-03-28" },
  { id: 9, subject: "Música", class: "1A", teacher: "Jane Smith", dueDate: "2026-04-01" },
  { id: 10, subject: "Arte", class: "3B", teacher: "Ana Santiago", dueDate: "2026-04-05" },
];

export const resultsData = [
  { id: 1, student: "Joãozinho Silva", subject: "Matemática", score: 85, type: "Prova", date: "2026-02-15" },
  { id: 2, student: "Maria Oliveira", subject: "Inglês", score: 92, type: "Prova", date: "2026-02-15" },
  { id: 3, student: "Pedro Santos", subject: "Biologia", score: 78, type: "Tarefa", date: "2026-02-18" },
  { id: 4, student: "Ana Costa", subject: "Física", score: 95, type: "Prova", date: "2026-02-20" },
  { id: 5, student: "Lucas Ferreira", subject: "História", score: 67, type: "Tarefa", date: "2026-02-22" },
  { id: 6, student: "Camila Rocha", subject: "Química", score: 88, type: "Prova", date: "2026-02-25" },
  { id: 7, student: "Gabriel Lima", subject: "Geografia", score: 73, type: "Tarefa", date: "2026-02-28" },
  { id: 8, student: "Isabela Mendes", subject: "Literatura", score: 91, type: "Prova", date: "2026-03-01" },
  { id: 9, student: "Rafael Almeida", subject: "Música", score: 86, type: "Tarefa", date: "2026-03-05" },
  { id: 10, student: "Larissa Souza", subject: "Arte", score: 94, type: "Prova", date: "2026-03-08" },
];

export const attendanceData = [
  { id: 1, student: "Joãozinho Silva", date: "2026-02-27", status: "Presente" as const, class: "1B" },
  { id: 2, student: "Maria Oliveira", date: "2026-02-27", status: "Presente" as const, class: "2A" },
  { id: 3, student: "Pedro Santos", date: "2026-02-27", status: "Ausente" as const, class: "1B" },
  { id: 4, student: "Ana Costa", date: "2026-02-27", status: "Presente" as const, class: "3C" },
  { id: 5, student: "Lucas Ferreira", date: "2026-02-27", status: "Atrasado" as const, class: "2A" },
  { id: 6, student: "Camila Rocha", date: "2026-02-26", status: "Presente" as const, class: "1B" },
  { id: 7, student: "Gabriel Lima", date: "2026-02-26", status: "Presente" as const, class: "3C" },
  { id: 8, student: "Isabela Mendes", date: "2026-02-26", status: "Ausente" as const, class: "2A" },
  { id: 9, student: "Rafael Almeida", date: "2026-02-26", status: "Presente" as const, class: "1B" },
  { id: 10, student: "Larissa Souza", date: "2026-02-26", status: "Atrasado" as const, class: "3C" },
];

export const messagesData = [
  { id: 1, from: "João Silva", to: "Admin", subject: "Reunião pedagógica", message: "Precisamos agendar a reunião pedagógica do mês.", date: "2026-02-27", read: false },
  { id: 2, from: "Fernanda Oliveira", to: "João Silva", subject: "Nota da Maria", message: "Gostaria de entender a nota da Maria na última prova.", date: "2026-02-26", read: true },
  { id: 3, from: "Admin", to: "Todos", subject: "Feriado escolar", message: "A escola estará fechada no dia 03/03.", date: "2026-02-25", read: true },
  { id: 4, from: "Miguel Geller", to: "Admin", subject: "Material de laboratório", message: "Precisamos repor os materiais do laboratório de biologia.", date: "2026-02-24", read: false },
  { id: 5, from: "Carlos Silva", to: "Jayme Franco", subject: "Desempenho do filho", message: "Como está o desempenho do Joãozinho em história?", date: "2026-02-23", read: true },
  { id: 6, from: "Admin", to: "Professores", subject: "Conselho de classe", message: "O conselho de classe será na sexta-feira às 14h.", date: "2026-02-22", read: true },
  { id: 7, from: "Ana Santiago", to: "Admin", subject: "Projeto de artes", message: "Vou precisar de um espaço extra para o projeto de artes.", date: "2026-02-21", read: false },
  { id: 8, from: "Patrícia Costa", to: "Admin", subject: "Transporte escolar", message: "Há mudança nos horários do transporte escolar?", date: "2026-02-20", read: true },
  { id: 9, from: "Derek Briggs", to: "Admin", subject: "Excursão literária", message: "Proposta de excursão à Feira do Livro para turmas 4B e 5A.", date: "2026-02-19", read: false },
  { id: 10, from: "Admin", to: "Responsáveis", subject: "Calendário 2026", message: "Segue o calendário escolar atualizado para 2026.", date: "2026-02-18", read: true },
];

export const announcementsData = [
  { id: 1, title: "Início do semestre", description: "As aulas do segundo semestre começam no dia 10 de março.", date: "2026-02-27", class: "Todas" },
  { id: 2, title: "Feira de ciências", description: "A feira de ciências acontecerá no dia 20 de março. Inscrições abertas.", date: "2026-02-25", class: "3° ano" },
  { id: 3, title: "Reunião de pais", description: "Reunião de pais e mestres no dia 15 de março às 19h.", date: "2026-02-24", class: "Todas" },
  { id: 4, title: "Campeonato esportivo", description: "Campeonato inter-turmas de futsal e vôlei. Inscrições na secretaria.", date: "2026-02-22", class: "4° e 5° ano" },
  { id: 5, title: "Atualização do sistema", description: "O sistema ficará em manutenção no sábado das 22h às 06h.", date: "2026-02-20", class: "Todas" },
  { id: 6, title: "Prova de recuperação", description: "As provas de recuperação acontecerão entre 25 e 28 de março.", date: "2026-02-18", class: "Todas" },
  { id: 7, title: "Excursão ao museu", description: "Excursão ao Museu de História Natural para turmas do 2° ano.", date: "2026-02-15", class: "2° ano" },
  { id: 8, title: "Uniforme novo", description: "O novo uniforme escolar já está disponível na secretaria.", date: "2026-02-12", class: "Todas" },
  { id: 9, title: "Vacinação", description: "Campanha de vacinação na escola no dia 05 de março.", date: "2026-02-10", class: "Todas" },
  { id: 10, title: "Matrículas abertas", description: "Matrículas para o próximo ano já estão abertas.", date: "2026-02-08", class: "Todas" },
];

export const calendarEvents = [
  // === SEGUNDA-FEIRA – 02/02/2026 ===
  {
    title: "Matemática",
    allDay: false,
    start: new Date(2026, 1, 2, 7, 30),
    end: new Date(2026, 1, 2, 8, 50),
    type: "math",
    teacher: "João Silva",
    room: "Sala 101",
  },
  {
    title: "Inglês",
    allDay: false,
    start: new Date(2026, 1, 2, 9, 0),
    end: new Date(2026, 1, 2, 9, 45),
    type: "english",
    teacher: "Allan Preto",
    room: "Sala 205",
  },
  {
    title: "Biologia",
    allDay: false,
    start: new Date(2026, 1, 2, 10, 0),
    end: new Date(2026, 1, 2, 11, 20),
    type: "biology",
    teacher: "Miguel Geller",
    room: "Lab 1",
  },
  // === TERÇA-FEIRA – 03/02/2026 ===
  {
    title: "Física",
    allDay: false,
    start: new Date(2026, 1, 3, 7, 30),
    end: new Date(2026, 1, 3, 8, 50),
    type: "physics",
    teacher: "Joana Santos",
    room: "Lab 2",
  },
  {
    title: "Química",
    allDay: false,
    start: new Date(2026, 1, 3, 9, 0),
    end: new Date(2026, 1, 3, 10, 20),
    type: "chemistry",
    teacher: "Joana Santos",
    room: "Lab 3",
  },
  {
    title: "História",
    allDay: false,
    start: new Date(2026, 1, 3, 10, 30),
    end: new Date(2026, 1, 3, 11, 50),
    type: "history",
    teacher: "Jayme Franco",
    room: "Sala 102",
  },
  // === QUARTA-FEIRA – 04/02/2026 ===
  {
    title: "Geografia",
    allDay: false,
    start: new Date(2026, 1, 4, 7, 30),
    end: new Date(2026, 1, 4, 8, 50),
    type: "geography",
    teacher: "Jane Smith",
    room: "Sala 103",
  },
  {
    title: "Literatura",
    allDay: false,
    start: new Date(2026, 1, 4, 9, 0),
    end: new Date(2026, 1, 4, 10, 20),
    type: "literature",
    teacher: "Derek Briggs",
    room: "Sala 204",
  },
  {
    title: "Matemática",
    allDay: false,
    start: new Date(2026, 1, 4, 10, 30),
    end: new Date(2026, 1, 4, 11, 50),
    type: "math",
    teacher: "Ofélia Castro",
    room: "Sala 101",
  },
  // === QUINTA-FEIRA – 05/02/2026 ===
  {
    title: "Música",
    allDay: false,
    start: new Date(2026, 1, 5, 7, 30),
    end: new Date(2026, 1, 5, 8, 50),
    type: "music",
    teacher: "Jane Smith",
    room: "Auditório",
  },
  {
    title: "Arte",
    allDay: false,
    start: new Date(2026, 1, 5, 9, 0),
    end: new Date(2026, 1, 5, 10, 20),
    type: "art",
    teacher: "Ana Santiago",
    room: "Ateliê",
  },
  {
    title: "Física",
    allDay: false,
    start: new Date(2026, 1, 5, 10, 30),
    end: new Date(2026, 1, 5, 11, 50),
    type: "physics",
    teacher: "Ana Santiago",
    room: "Lab 2",
  },
  // === SEXTA-FEIRA – 06/02/2026 ===
  {
    title: "Inglês",
    allDay: false,
    start: new Date(2026, 1, 6, 7, 30),
    end: new Date(2026, 1, 6, 8, 50),
    type: "english",
    teacher: "Allan Preto",
    room: "Sala 205",
  },
  {
    title: "Biologia",
    allDay: false,
    start: new Date(2026, 1, 6, 9, 0),
    end: new Date(2026, 1, 6, 10, 20),
    type: "biology",
    teacher: "João Glover",
    room: "Lab 1",
  },
  {
    title: "História",
    allDay: false,
    start: new Date(2026, 1, 6, 10, 30),
    end: new Date(2026, 1, 6, 11, 50),
    type: "history",
    teacher: "Jayme Franco",
    room: "Sala 102",
  },
];